version: 2
registries:
  maven-google:
    type: maven-repository
    url: https://maven.google.com
    username: ""
    password: ""
updates:
  # Verify Gradle dependencies
  - package-ecosystem: "gradle"
    directories:
      - "/android"
    registries:
      - maven-google
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "com.wbd.*:*"
      - dependency-name: "com.turner.*:*"
      - dependency-name: "com.mapbox.*:*"
    groups:
      minor-version-updates:
        dependency-type: "production"
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      production-security-updates:
        dependency-type: "production"
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"

  # Verify Github Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
