[versions]

# Library Versions

accompanistSwiperefresh = "0.36.0"
activityCompose = "1.7.2"
adtechSdk = "5.24.0"
afAndroidSdk = "6.17.0"
adobeAnalytics = "3.0.2"
adobeCore = "3.9.0"
adobeIdentity = "3.0.2"
adobeLifecycle = "3.0.2"
adobeSignal = "3.0.1"
androidSdk = "1.7.4"
androidAnalytics = "6.15.0"
androidRetrofuture = "1.7.4"
androidxMacroBenchmark = "1.5.0-alpha07"
annotation = "1.8.1"
appcompat = "1.8.0"
assertkJvm = "0.28.1"
authPicker = "2.22.3-1"
benchmarkMacroJunit4 = "1.5.0"
billingKtx = "9.1.0"
biometric = "1.4.0-alpha07"
boltPlaybackinfoResolver = "2.6.0"
bouquet = "1.1.2"
browser = "1.10.0"
cardview = "1.0.0"
composeBom = "2026.09.00"
composeLintChecks = "1.6.0"
constraintlayout = "2.2.2"
constraintlayoutCompose = "1.1.2"
coreKtx = "1.19.0"
coreKtxVersion = "1.7.0"
coreTesting = "2.2.0"
credentials = "1.5.0"
credentialsPlayServicesAuth = "1.5.0"
googleid = "1.2.1"
datastorePreferences = "1.1.7"
desugar_jdk_libs = "2.1.5"
espressoCore = "3.7.0"
firebaseBom = "34.19.0"
firebaseCrashlyticsGradle = "3.0.8"
fragmentKtx = "1.9.0"
fragmentCompose = "1.9.0"
freeviewBlock = "2.22.3-0"
glide = "5.0.9"
glob = "0.9.0"
googleServices = "4.5.0"
gradle = "9.1.0"
gradleTestRetry = "1.6.6"
gson = "2.14.0"
hilt = "2.60.1"
hiltCompilerVersion = "1.4.0"
hiltLifecycleViewmodelCompose = "1.4.0"
hiltWork = "1.4.0"
installreferrer = "2.2"
jsr250Api = "1.0"
junit = "4.13.2"
junitKtx = "1.3.0"
junitVersion = "1.3.0"
kotlinTestJunit = "2.4.20"
kotlinxCollectionsImmutableJvm = "0.5.2"
kotlinxCoroutines = "1.11.0"
kotlinxSerializationJson = "1.11.0"
ktorClientCore = "2.3.4"
ktorClientOkhttp = "2.3.4"
landscapistGlide = "1.6.1"
leakcanaryAndroidNoOp = "1.6.3"
legacySupportV4 = "1.0.0"
lifecycle = "2.6.2"
lifecycleExtensions = "2.2.0"
lottieCompose = "6.7.1"
beamNetwork = "0.9.3"
mapbox = "11.18.0"
material = "1.14.0"
materialIconsExtended = "1.7.8"
media3Exoplayer = "1.11.1"
media3Session = "1.11.1"
media3Ui = "1.11.1"
mediaMelon = "2.17.0"
mockitoCore = "5.23.0"
mockitoKotlin = "6.3.0"
mockk = "1.14.11"
moshi = "1.15.2"
moshiKotlinCodegen = "1.15.2"
mux = "4.13.0"
navigation = "2.10.1"
okhttp = "5.5.0"
optimizelyAndroidSdk = "5.4.0"
orgJacocoCore = "0.8.15"
perfPlugin = "2.0.2"
splashscreen = "1.2.0"

# Plugin Versions

detekt = "2.0.0-alpha.5"
devtoolsKsp = "2.3.12"
kotlinter = "5.7.0"
kotlinPlugin = "2.4.20"
playerActivityIndicatorOverlay = "2.3.0"
playerBlock = "2.22.3-0"
playerCommon = "7.2.0"
playerControlsOverlay = "4.11.0"
playerCore = "6.2.0"
playerErrorOverlay = "3.4.0"
playerUiCommon = "4.1.0"
playerUiCore = "3.13.0"
playServicesAds = "25.5.0"
playServicesGcm = "17.0.0"
preferenceKtx = "1.2.1"
previewThumbnailOverlay = "3.7.0"
progressReporter = "2.3.2"
recyclerview = "1.4.0"
retrofit2KotlinxSerializationConverter = "1.0.0"
robolectric = "4.17"
runner = "1.0.2"
rules = "1.0.2"
rxandroid = "1.2.1"
rxjava = "1.3.8"
rxjavaDebug = "1.0.3"
securityCrypto = "1.1.0-alpha03"
snapper = "0.3.0"
snowplowAndroidTracker = "6.4.1"
squareupRetrofit = "3.0.0"
stdLibBlock = "2.21.0-2"
timber = "5.0.1"
trackselectionOverlay = "3.5.0"
turbine = "1.2.1"
uiautomator = "2.4.0"
urbanairshipAutomation = "20.4.0"
userprofile = "3.0.1"
verticalPlayerControlsOverlay = "3.5.0"
viewpump = "2.1.1"
webkit = "1.5.0"
window = "1.3.0"
workRuntime = "2.7.1"

[libraries]
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefresh" }
adapter-rxjava = { module = "com.squareup.retrofit2:adapter-rxjava", version.ref = "squareupRetrofit" }
adtech-sdk = { module = "com.wbd.adtech:adtech-sdk", version.ref = "adtechSdk" }
af-android-sdk = { module = "com.appsflyer:af-android-sdk", version.ref = "afAndroidSdk" }
adobe-core = { module = "com.adobe.marketing.mobile:core", version.ref = "adobeCore" }
adobe-identity = { module = "com.adobe.marketing.mobile:identity", version.ref = "adobeIdentity" }
adobe-lifecycle = { module = "com.adobe.marketing.mobile:lifecycle", version.ref = "adobeLifecycle" }
adobe-signal = { module = "com.adobe.marketing.mobile:signal", version.ref = "adobeSignal" }
analytics = { module = "com.adobe.marketing.mobile:analytics", version.ref = "adobeAnalytics" }
android-analytics = { module = "com.comscore:android-analytics", version.ref = "androidAnalytics" }
android-ndk27 = { module = "com.mapbox.maps:android-ndk27", version.ref = "mapbox" }
android-retrofuture = { module = "net.sourceforge.streamsupport:android-retrofuture", version.ref = "androidRetrofuture" }
android-sdk = { module = "com.github.chartbeat:android_sdk", version.ref = "androidSdk" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-core-ktx = { module = "androidx.test:core-ktx", version.ref = "coreKtxVersion" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-fragment-compose = { module = "androidx.fragment:fragment-compose", version.ref = "fragmentCompose" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompilerVersion" }
androidx-hilt-lifecycle-viewmodel-compose = { module = "androidx.hilt:hilt-lifecycle-viewmodel-compose", version.ref = "hiltLifecycleViewmodelCompose" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junitKtx" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-material = { module = "androidx.compose.material:material" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3Session" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Ui" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigation" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen"}
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
assertk-jvm = { module = "com.willowtreeapps.assertk:assertk-jvm", version.ref = "assertkJvm" }
auth-picker = { module = "com.turner.top:auth-picker", version.ref = "authPicker" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingKtx" }
bolt-playbackinfo-resolver = { module = "com.wbd.player:bolt-playbackinfo-resolver", version.ref = "boltPlaybackinfoResolver" }
bouquet = { module = "io.github.grizzi91:bouquet", version.ref = "bouquet" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-lint-checks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "composeLintChecks" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "squareupRetrofit" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
freeview-block = { module = "com.turner.top:freeview-block", version.ref = "freeviewBlock" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
glide-okhttp3-integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }
glob = { module = "com.hrakaroo:glob", version.ref = "glob" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
installreferrer = { module = "com.android.installreferrer:installreferrer", version.ref = "installreferrer" }
jsr250-api = { module = "javax.annotation:jsr250-api", version.ref = "jsr250Api" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinTestJunit" }
kotlinx-collections-immutable-jvm = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm", version.ref = "kotlinxCollectionsImmutableJvm" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorClientOkhttp" }
landscapist-glide = { module = "com.github.skydoves:landscapist-glide", version.ref = "landscapistGlide" }
leakcanary-android-no-op = { module = "com.squareup.leakcanary:leakcanary-android-no-op", version.ref = "leakcanaryAndroidNoOp" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
beam-network-client-main = { module = "com.wbd.beam.network.client:main", version.ref = "beamNetwork" }
maps-compose-ndk27 = { module = "com.mapbox.extension:maps-compose-ndk27", version.ref = "mapbox" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
media-melon = { module = "com.wbd.player.plugins:mediamelon", version.ref = "mediaMelon" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshiKotlinCodegen" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
mux = { module = "com.wbd.player.plugins:mux", version.ref = "mux" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp-urlconnection = { module = "com.squareup.okhttp3:okhttp-urlconnection" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
optimizely-android-sdk = { module = "com.optimizely.ab:android-sdk", version.ref = "optimizelyAndroidSdk"}
org-jacoco-core = { module = "org.jacoco:org.jacoco.core", version.ref = "orgJacocoCore" }
perf-plugin = { module = "com.google.firebase:perf-plugin", version.ref = "perfPlugin" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
play-services-gcm = { module = "com.google.android.gms:play-services-gcm", version.ref = "playServicesGcm" }
player-activity-indicator-overlay = { module = "com.wbd.player.overlays.beam:player-activity-indicator-overlay", version.ref = "playerActivityIndicatorOverlay" }
player-block = { module = "com.turner.top:player-block", version.ref = "playerBlock" }
player-common = { module = "com.wbd.player:player-common", version.ref = "playerCommon" }
player-controls-overlay = { module = "com.wbd.player.overlays.beam:player-controls-overlay", version.ref = "playerControlsOverlay" }
player-core = { module = "com.wbd.player:player-core", version.ref = "playerCore" }
player-error-overlay = { module = "com.wbd.player.overlays.beam:player-error-overlay", version.ref = "playerErrorOverlay" }
player-ui-common = { module = "com.wbd.player:player-ui-common", version.ref = "playerUiCommon" }
player-ui-core = { module = "com.wbd.player:player-ui-core", version.ref = "playerUiCore" }
preview-thumbnail-overlay = { module = "com.wbd.player.overlays.beam:preview-thumbnail-overlay", version.ref = "previewThumbnailOverlay" }
progress-reporter = { module = "com.wbd.player.plugins.beam:progress-reporter", version.ref = "progressReporter" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "squareupRetrofit" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "squareupRetrofit" }
retrofit2-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "squareupRetrofit" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
rules = { module = "com.android.support.test:rules", version.ref = "rules" }
runner = { module = "com.android.support.test:runner", version.ref = "runner" }
rxandroid = { module = "io.reactivex:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex:rxjava", version.ref = "rxjava" }
rxjava-debug = { module = "io.reactivex:rxjava-debug", version.ref = "rxjavaDebug" }
snapper = { module = "dev.chrisbanes.snapper:snapper", version.ref = "snapper" }
snowplow-android-tracker = { module = "com.snowplowanalytics:snowplow-android-tracker", version.ref = "snowplowAndroidTracker" }
std-lib-block = { module = "com.turner.top:std-lib-block", version.ref = "stdLibBlock" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
trackselection-overlay = { module = "com.wbd.player.overlays.beam:trackselection-overlay", version.ref = "trackselectionOverlay" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
ui = { module = "androidx.compose.ui:ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
urbanairship-automation = { module = "com.urbanairship.android:urbanairship-automation", version.ref = "urbanairshipAutomation" }
userprofile = { module = "com.adobe.marketing.mobile:userprofile", version.ref = "userprofile" }
vertical-player-controls-overlay = { module = "com.wbd.player.overlays.beam:vertical-player-controls-overlay", version.ref = "verticalPlayerControlsOverlay" }
viewpump = { module = "io.github.inflationx:viewpump", version.ref = "viewpump" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
detekt-api = { module = "dev.detekt:detekt-api", version.ref = "detekt" }
detekt-test = { module = "dev.detekt:detekt-test", version.ref = "detekt" }

[plugins]
baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidxMacroBenchmark"}
detekt = { id = "dev.detekt", version.ref = "detekt"}
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtoolsKsp"}
jmailen-kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinPlugin"}
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinPlugin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinPlugin" }
gradle-test-retry = { id = "org.gradle.test-retry", version.ref = "gradleTestRetry"}
